[package]
name = "oicana-example-rust-axum"
description = "Example application using the Oicana Rust integration for PDF templating"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/oicana/oicana-example-rust-axum"
license = "MIT"

[dependencies]
oicana = { version = "0.8.0", features = ["packed", "pdf", "png"] }

axum = { version = "0.8.4", features = ["macros", "multipart"] }
tokio = {version = "1", features = ["full"]}
tokio-util = {version = "0.7.15", features = ["io"]}
tower = "0.5.2"
tower-http = {version = "0.6.6", features = ["trace", "timeout", "cors", "compression-full", "decompression-full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dashmap = "6.1.0"
anyhow = "1.0.100"
serde = { version = "1.0.225", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
utoipa = {version = "5.4.0", features= ["axum_extras", "uuid"] }
utoipa-axum = {version = "0.2.0"}
utoipa-swagger-ui = {version = "9.0.2", features= ["axum"] }
serde_json = "1.0.145"
