name: CI

on:
  pull_request:
  push:
    branches: 
     - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  crates-ci:
    name: Format, linting, and tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: check format
        run: cargo fmt --all -- --check
      - name: run clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings
      - name: check
        run: cargo check --all-features --all-targets
      - name: run tests
        run: cargo test --all-targets --all-features

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v6
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.35.5

  validate-links:
    name: Check for dead links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: check readme links
        run: npx linkinator README.md --config .github/linkinator.config.json
